apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
     app: testapp

spec:
   containers:
     - name: payara-micro-javaee8-test1
       image: saber66/payara-micro-javaee8-test1
       ports:
         - containerPort: 8080
